# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Gentoo Theme"
license = "MIT"
licenselink = "https://github.com/d-kusk/hugo-gentoo-theme/blob/master/LICENSE.md"
description = "It is the theme of Hugo. Created by imagining the Gentoo penguin."
homepage = "https://github.com/d-kusk/hugo-gentoo-theme"
tags = ["blog", "responsive"]
features = ["blog", "themes", "responsive", "Google Analytics"]
min_version = 0.19

[author]
  name = "Daisuke Konishi"
  homepage = "https://blog.daisukekonishi.com"

# If porting an existing theme
[original]
  name = "Gentoo"
  homepage = "https://github.com/d-kusk/hugo-gentoo-theme/"
  repo = "https://github.com/d-kusk/hugo-gentoo-theme/"

[params]
  dateformat = "Jan 2, 2006" # Optional
